apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  tssc/gitops: m9qbelqyf-java-springboot 
  janus-idp.io/tekton: m9qbelqyf-java-springboot
  backstage.io/kubernetes-id: m9qbelqyf-java-springboot
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: m9qbelqyf-java-springboot
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml